name: ecom
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  async: ^2.9.0
  collection: ^1.16.0
  # fake_async: ^1.3.1
  firebase_core: ^2.1.0
  # material_color_utilities: ^0.1.5
  # path: ^1.8.2
  # plugin_platform_interface: ^2.1.3
  cloud_firestore: ^4.0.2
  firebase_auth: ^4.0.2
  provider: ^6.0.4
  http: ^0.13.4
  flutter_stripe: ^2.4.0
  cached_network_image: ^3.2.0
  json_annotation: ^4.7.0
  firebase_database: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.5
  build_runner: ^2.1.8

  flutter_lints: ^2.0.0

flutter:

  assets:
    - assets/shoe.jpg
    - assets/logo.jpg
    - assets/img.jpg
    - assets/config/
  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Bold.ttf
        - asset: fonts/DMSans-Medium.ttf
        - asset: fonts/DMSans-Regular.ttf

  uses-material-design: true

